### ISSUE TITLE
Question about formula in paper

### ISSUE THREAD

**Issue by mikelmh025** [raminnakhli/Decoupled-Contrastive-Learning#2]
![image](https://user-images.githubusercontent.com/38229852/142364448-73be1938-b898-43db-8226-1d8375b9c9f5.png)

I wonder in the proof of Proposition 1. If there should include a (2)?

**Comment by raminnakhli** [comment]
Yes. I think that's correct. 
PS: I think there are a few mistakes in the proof as well. I suggest reading the reviews on OpenReview ([link](https://openreview.net/forum?id=sxpUavxXE0v)).

**Comment by raminnakhli** [comment]
I'll close this issue as there hasn't been an activity for a while. Please open another issue if this is not responded.
