### ISSUE TITLE
Was trying to work with the formula

### ISSUE THREAD

**Issue by mikelmh025** [raminnakhli/Decoupled-Contrastive-Learning#3]
Hi there,

Great work! I am trying to learn from the formula and walk through the proof of propositions. I was trying to find the derivatives of the loss function and encountered finding the partial derivative of the cosine similarity term. By comparing my answer and steps in the paper I kind of get this result (as the image shows). 

I am not quite sure if that is correct and how that works. Would you mind help me a bit with this?

![image](https://user-images.githubusercontent.com/38229852/142365284-26d336d0-882b-4f32-b1a3-0399cbe21fa6.png)

**Comment by raminnakhli** [comment]
Hi and thank you!
The second line is correct as the `z_j` is independent of `z_i`. However, in the first line, `z^1_i` and `z^2_i` are augmentations of the same image which means they are dependent on each other. Therefore, the first term is not necessarily correct.
I hope it would have helped.

**Comment by raminnakhli** [comment]
I'll close this issue as there hasn't been an activity for a while. Please open another issue if this is not responded.
