### ISSUE TITLE
About the optimization setting

### ISSUE THREAD

**Issue by huangzizheng01** [raminnakhli/Decoupled-Contrastive-Learning#7]
Hello, Thanks for your good work! I'd like to know if the cosine annealing schedule is also applied to the small-scale dataset experiments of CIFAR and STL10?

**Comment by raminnakhli** [comment]
Hi, thanks for the query. The SimCLR implementation is taken from [this link](https://github.com/leftthomas/SimCLR), which uses a fixed learning rate. So, the cosine scheduler is not applied.

**Comment by huangzizheng01** [comment]
Thank you
