### ISSUE TITLE
Official Imagenet-100 Download Links

### ISSUE THREAD

**Issue by gurdeepmaurya** [raminnakhli/Decoupled-Contrastive-Learning#8]
Hi,

I'm trying to find an official source for the Imagenet-100 dataset used in this paper.

Regards

**Comment by raminnakhli** [comment]
Hi @gurdeepmaurya,

sorry for the late reply. It might be best to contact the author for this case. That being said, doing a quick search, I found this link that might be helpful.
https://www.kaggle.com/datasets/ambityga/imagenet100
