### ISSUE TITLE
negative loss value

### ISSUE THREAD

**Issue by wqtwjt1996** [raminnakhli/Decoupled-Contrastive-Learning#9]
Can you tell me why exist loss with negative values? Is that a potential bug in your code?

**Comment by raminnakhli** [comment]
Hi @wqtwjt1996, thanks for the question. This comes from the loss function itself, and it's not a bug. Contrastive loss is always bound to 0 and 1. But when you remove the coupling term, these bounds don't stand anymore and it can have higher values than 1. This means that the negative log of loss will become negative. 
Hope it helps
